### PR TITLE
add github actions workflow

### PR DESCRIPTION
**Pull request by asahasrabuddhe**

### CODE REVIEW

**Comment by knadh** [comment]
This is nice. Can you squash the two commits to one (because they're essentially the same thing) though?

**Comment by asahasrabuddhe** [comment]
This one is WIP. I will squash eventually once it is finalised :)

**Comment by knadh** [comment]
I merged the other PR but this one seems to have the same commits as the other one. Could you rebase from master and resend the PR just with the workflow patch?

**Comment by asahasrabuddhe** [comment]
No problem. I think let's close this one. I will create a new one :)

**Pull request closed without merging**
